In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from bs4 import BeautifulSoup

In [10]:
API_ID = "B0D623B91529E3A78E564AEBA"

In [11]:
response = requests.get(f"https://developer.trimet.org/ws/V1/arrivals?locIDs=6849,6850&appID={API_ID}")
response.headers.get('content-type')

'text/xml'

In [31]:
vehicle_locations = requests.get(f"https://developer.trimet.org/ws/v2/vehicles?appID={API_ID}")
vehicle_locations.headers.get('content-type')

'application/json'

In [51]:
arrivals = requests.get(f"https://developer.trimet.org/ws/v2/arrivals?locIDs=7618,7772&appID={API_ID}")
arrivals.headers.get('content-type')

'application/json'

In [52]:
route_config = requests.get(f"https://developer.trimet.org/ws/v1/routeConfig?json=true&appID={API_ID}")
route_config.headers.get('content-type')

'application/json'

In [53]:
df_locs = pd.DataFrame(vehicle_locations.json()["resultSet"]['vehicle'])
df_locs.head(5)

,expires,signMessage,serviceDate,loadPercentage,latitude,nextStopSeq,source,type,blockID,signMessageLong,...,bearing,garage,tripID,delay,extraBlockID,messageCode,lastStopSeq,vehicleID,time,offRoute
0,1649282206964,Green Line to Clackamas,1649228400000,None,45.531514,16.0,tab,rail,9082,MAX Green Line to Clackamas Town Center,...,150,RUBY,11434563,-90.0,None,1080.0,15.0,101,1649281718163,False
1,1649282383786,Blue to Hillsboro,1649228400000,None,45.501881,1.0,tab,rail,9005,MAX Blue Line to Hillsboro,...,285,RUBY,11432372,0.0,None,1010.0,45.0,102,1649281717680,False
2,1649281964209,12 To Tigard TC,1649228400000,None,45.531744,24.0,vm,bus,1202,12 Barbur/Sandy Blvd to Tigard TC via Portlan...,...,238,CENTER,11422083,-146.0,None,239.0,23.0,4204,1649281727899,False
3,1649282620065,Orange Line to City Ctr/Expo,1649228400000,None,45.430770,1.0,tab,rail,9062,MAX Orange Line to City Center/Expo Center,...,354,RUBY,11435990,0.0,None,1094.0,17.0,109,1649281703365,False
4,1649281951142,33 To Clackamas Town Center,1649228400000,None,45.321977,1.0,vm,bus,3308,33 McLoughlin/King Rd to Clackamas TC via Mil...,...,33,CENTER,11425013,0.0,None,428.0,NaN,4208,1649281712564,False

In [62]:
df_arrivals = pd.DataFrame(arrivals.json()["resultSet"]['arrival'])
df_arrivals.head(5)

,feet,inCongestion,departed,scheduled,loadPercentage,shortSign,estimated,detoured,tripID,dir,...,route,piece,fullSign,id,dropOffOnly,vehicleID,showMilesAway,locid,newTrip,status
0,0.0,None,True,1649283490000,NaN,Green Line to City Ctr,1.649283e+12,True,11434984,1,...,200,1,MAX Green Line to City Center/PSU,11434984_55090_6,False,305,False,7618,False,estimated
1,0.0,False,True,1649283360000,NaN,44 Mocks Crest to St Johns,1.649283e+12,True,11425405,1,...,44,1,44 Mocks Crest to St Johns,11425405_54960_6,False,3104,False,7772,False,estimated
2,2318.0,False,True,1649283676000,NaN,19 Gateway TC,1.649284e+12,True,11423466,1,...,19,1,19 Glisan to Gateway TC,11423466_55276_6,False,3310,False,7772,False,estimated
3,1886.0,False,True,1649283791000,NaN,12 Parkrose TC,1.649284e+12,True,11422266,1,...,12,1,12 Sandy Blvd to Parkrose TC,11422266_55391_6,False,3706,False,7772,False,estimated
4,4759.0,None,True,1649284030000,NaN,Orange Line to Milwaukie,1.649284e+12,True,11436395,1,...,290,1,MAX Orange Line to Milwaukie,11436395_55630_6,False,527,False,7618,False,estimated

In [63]:
df_routes = pd.DataFrame(route_config.json()["resultSet"]['route'])
df_routes.head(5)

,routeColor,frequentService,route,detour,id,type,desc,routeSortOrder
0,084C8D,True,100,True,100,R,MAX Blue Line,100
1,008852,True,200,True,200,R,MAX Green Line,110
2,F58220,True,290,True,290,R,MAX Orange Line,115
3,D81526,True,90,True,90,R,MAX Red Line,120
4,F8C213,True,190,NaN,190,R,MAX Yellow Line,130

In [65]:
#number of buses that are arriving at PSU within the next 20 mins
print(len(df_arrivals))

14